[2022-10-28 00:00:03,634] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.create_table scheduled__2022-10-27T00:00:00+00:00 [queued]>
[2022-10-28 00:00:03,653] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.create_table scheduled__2022-10-27T00:00:00+00:00 [queued]>
[2022-10-28 00:00:03,654] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-28 00:00:03,655] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-28 00:00:03,656] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-28 00:00:03,670] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_table> on 2022-10-27 00:00:00+00:00
[2022-10-28 00:00:03,683] {standard_task_runner.py:52} INFO - Started process 8333 to run task
[2022-10-28 00:00:03,686] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'create_table', 'scheduled__2022-10-27T00:00:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmptnsjk79y', '--error-file', '/tmp/tmpu85204ia']
[2022-10-28 00:00:03,688] {standard_task_runner.py:80} INFO - Job 36: Subtask create_table
[2022-10-28 00:00:03,729] {task_command.py:369} INFO - Running <TaskInstance: user_processing.create_table scheduled__2022-10-27T00:00:00+00:00 [running]> on host 19f0eed441f9
[2022-10-28 00:00:03,786] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-10-27T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-27T00:00:00+00:00
[2022-10-28 00:00:03,797] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-10-28 00:00:03,802] {dbapi.py:208} INFO - Running statement: 
        CREATE TABLE IF NOT EXISTS users (
            firstname TEXT NOT NULL,
            lastname TEXT NOT NULL,
            country TEXT NOT NULL,
            username TEXT NOT NULL,
            password TEXT NOT NULL,
            email TEXT NOT NULL
        );
        , parameters: None
[2022-10-28 00:00:03,807] {postgres.py:94} INFO - NOTICE:  relation "users" already exists, skipping

[2022-10-28 00:00:03,815] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=create_table, execution_date=20221027T000000, start_date=20221028T000003, end_date=20221028T000003
[2022-10-28 00:00:03,863] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-28 00:00:03,893] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
